### ISSUE TITLE
Installation of boilerplate is failed

### ISSUE THREAD

**Issue by Lazur** [docksal/boilerplate-symfony-webapp#2]
Hi, 
I tried to use boilerplate and it doesn't works for me. The steps and results are below:
`fin project create` - 12
short results:
`Step 2  Initializing site...
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 107 installs, 0 updates, 0 removals`

`Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your Javascript dependencies!
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineCacheBundle" from namespace "Doctrine\Bundle\DoctrineCacheBundle".
!!  Did you forget a "use" statement for another namespace? in /var/www/src/Kernel.php:33
!!  Stack trace:
!!  #0 /var/www/vendor/symfony/http-kernel/Kernel.php(446): App\Kernel->registerBundles()
!!  #1 /var/www/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/vendor/symfony/framework-bundle/Console/Application.php(169): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /var/www/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /var/www/bin/console(39): Symfony\Component\Console\Application->run(Obj in /var/www/src/Kernel.php on line 33
!!
Script @auto-scripts was called via post-update-cmd`

**Comment by sarbazx** [comment]
Also some packages are deprecated 

![image](https://user-images.githubusercontent.com/5629946/104897965-19508b80-598a-11eb-93d7-c31e84fb0c7f.png)

**Comment by Lazur** [comment]
I'd like to add that docksal initiated into symfony 5 project is not working too. Web profiler is failed to load due to routing issues since routing is not working as well.

**Comment by sarbazx** [comment]
@lmakarov is symfony not supported by docksal anymore?

**Comment by lmakarov** [comment]
> is symfony not supported by docksal anymore?

Nah. Symfony is PHP. PHP is at Docksal's core.
This boilerplate has not been updated in 4 years. No wonders it does not initialize properly.

@sean-e-dietrich is this something you can take on?
